name: Linting, testing, building
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps: 
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build prod project
        run: npm run build:prod
        if: always()
      - name: linting ts
        run: npm run eslint
      - name: linting css
        if: always()
        run: npm run stylelint
      - name: unit testing
        if: always()
        run: npm run test:unit
      - name: build storybook
        if: always()
        run: npm run storybook:build
      - name: screenshot test
        if: always()
        run: npm run test:ui:ci